#Pandas The Data Science Power tool


Key concepts:
#Series and DataFrames

#read_csv(), head(), info(), describe()

#Filtering rows, selecting columns

#groupby(), value_counts(), sort_values()

In [1]:
#Pandas
#Python library for working with structured data like tables,spreadsheets,csv.
#it provides tools to analyze, clean and manipulate data efficiently
#to use it import it
import pandas as pd

In [9]:
#series(1 D data)
#Series is like a single column of data wih labels(like a column in excel)

scores = pd.Series([80,90,70],index=['X','Y','Z'])  #S capital
print(scores)

X    80
Y    90
Z    70
dtype: int64


In [6]:
#DataFrame(2 D table)
#think of dataframe as complete table with rows and columns

data = {
    "Name":["Sid","Jake","Amy"],
    "Math":[80,90,80],
    "Science":[85,88,75],
}

df = pd.DataFrame(data)
print(df)


   Name  Math  Science
0   Sid    80       85
1  Jake    90       88
2   Amy    80       75


In [10]:
#read_csv()

#to read a csv file
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.head()  #first 5 rows

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [12]:
df.info()  #to get the summary of the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [13]:
df.describe() #gives mean, max,etc (only for numerical columns)

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
#Question: Undesrtand all these statistics

In [17]:
#Selecting columns
df['Survived'].head(2)
df[['PassengerId','Survived']].head(2)

PassengerId  Survived
0            1         0
1            2         1

In [23]:
#filtering columns
df[(df['Survived'] == 1) & (df['Sex'] == 'male')].head()

PassengerId  Survived  Pclass                          Name   Sex   Age  \
17           18         1       2  Williams, Mr. Charles Eugene  male   NaN   
21           22         1       2         Beesley, Mr. Lawrence  male  34.0   
23           24         1       1  Sloper, Mr. William Thompson  male  28.0   
36           37         1       3              Mamee, Mr. Hanna  male   NaN   
55           56         1       1             Woolner, Mr. Hugh  male   NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
17      0      0  244373  13.0000   NaN        S  
21      0      0  248698  13.0000   D56        S  
23      0      0  113788  35.5000    A6        S  
36      0      0    2677   7.2292   NaN        C  
55      0      0   19947  35.5000   C52        S

In [24]:
#groupby

#group data by some column and apply some functions

df.groupby('Sex')['Age'].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [25]:
#value_counts
#counts how often a value comes in a column
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [28]:
#sorting

df[df["Sex"] == "female"].sort_values(by='Age',ascending=False).head(5)

PassengerId  Survived  Pclass  \
483          484         1       3   
275          276         1       1   
829          830         1       1   
366          367         1       1   
268          269         1       1   

                                                 Name     Sex   Age  SibSp  \
483                            Turkula, Mrs. (Hedwig)  female  63.0      0   
275                 Andrews, Miss. Kornelia Theodosia  female  63.0      1   
829         Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  female  60.0      1   
268     Graham, Mrs. William Thompson (Edith Junkins)  female  58.0      0   

     Parch    Ticket      Fare Cabin Embarked  
483      0      4134    9.5875   NaN        S  
275      0     13502   77.9583    D7        S  
829      0    113572   80.0000   B28      NaN  
366      0    110813   75.2500   D37        C  
268      1  PC 17582  153.4625  C125        S

In [ ]:
#Numpy basics
#NumPy (Numerical Python) is a fast, powerful library for numerical operations on arrays.

#Why use NumPy?

#Works like Python lists, but faster & more powerful.

#Great for math, ML, data analysis, and scientific computing.

In [29]:
#creating arrays
import numpy as np
a=np.array([1,2,3]) #1D array
b=np.array([[1,2],[3,4]])   #2D array
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [33]:
#array shape an type
print(a.shape)
print(b.shape)
print(a.dtype)

(3,)
(2, 2)
int64


In [36]:
#indexing and slicing
print(a[0])
print(b[1,0])

#slicing
print(a[0:1])

1
3
[1]


In [39]:
print(np.mean(b))
print(np.std(b))
print(np.sum(b))
print(np.max(b))
print(np.min(b))

2.5
1.118033988749895
10
4
1


In [40]:
#Broadcasting
#numpy allows operations between arrays of different shapes(without writing loops)
a =np.array([3,4,5])
b = a + 10
print(b)

[13 14 15]


In [44]:
#Why numpy is faster than list

list1=[1,2,3,4]
list2=[5,6,7,8]

list3=[list1[i] + list2[i] for i in range(4)]   #slow loop
print(list3)

#but with numpy
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = a + b   # Fast (vectorized)
print(c)


[6, 8, 10, 12]
[ 6  8 10 12]


Simple Analogy
Imagine you're cooking for 4 friends:

Without vectorization: You serve each person one by one (loop).

With vectorization: You serve everyone at once using a big tray (fast and efficient).